"""
Django settings for samantha_campaigns project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "234567890-fchgvjbkdgxfchgvjbklndxgfcghvjhbkln;mgfhjk"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # External deps
    "rest_framework",
    "corsheaders",
    # "phonenumber_field",
    "django_utz",


    # Local apps
    "api.apps.ApiConfig",
    "campaigns.apps.CampaignsConfig",
    "reports.apps.ReportsConfig"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_utz.middleware.DjangoUTZMiddleware',
]

ROOT_URLCONF = 'samantha_campaigns.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'samantha_campaigns.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'users.backends.DowellSessionIDAuthorizationBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# CSRF 

CSRF_COOKIE_SECURE = True 

CSRF_COOKIE_SAMESITE = 'Lax'

CSRF_TRUSTED_ORIGINS = ["http://*", "https://*"]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/filestorage/'

# media will be stored in filestorage folder
MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_URL)

STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL)

# Logging

LOG_PATH = os.path.join(BASE_DIR, "logs")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

APPEND_SLASH = True


#########################
# API SPECIFIC SETTINGS #
#########################

API_BASE_URL = "https://samanta100111.pythonanywhere.com/api/v1/"

PROJECT_NAME = "Samantha Campaigns"

PROJECT_EMAIL = "dowell@dowellresearch.uk"

PROJECT_API_KEY = "1b834e07-c68b-4bf6-96dd-ab7cdc62f07f"
# PROJECT_API_KEY = "1df59405-31c7-4f71-982f-bae848c61c3f"

WEBHOOK_PASSKEY = "1eb$fyirun-gh2j3go1n4u12@i"

DISABLE_DOWELL_AUTO_DEDUCT_CREDITS = True


###################
# DOWELL API URLs #
###################

DOWELL_GET_COORDINATES_URL = "https://100074.pythonanywhere.com/get-coords/"

DOWELL_USER_INFO_URL = "https://100014.pythonanywhere.com/api/userinfo/"

DOWELL_USER_SERVICE_KEY_URL = "https://100105.pythonanywhere.com/api/v3/user/"

DOWELL_PROCESS_SERVICES_URL = "https://100105.pythonanywhere.com/api/v3/process-services/"

DOWELL_MAIL_URL = "https://100085.pythonanywhere.com/api/uxlivinglab/email/"

DOWELL_EMAIL_VALIDATOR_URL = "https://100085.pythonanywhere.com/api/uxlivinglab/verify-email/"

DOWELL_WEBSITE_CRAWLER_URL = "https://www.uxlive.me/api/website-info-extractor/"


##########################
# DOWELL API SERVICE IDs #
##########################

DOWELL_MAIL_SERVICE_ID = "DOWELL10001"

DOWELL_SMS_SERVICE_ID = "DOWELL10037"

DOWELL_LOGIN_SERVICE_ID = "DOWELL10004"

DOWELL_SEARCH_IN_LIVING_LABS_SERVICE_ID = "DOWELL10023"

DOWELL_SAMANTHA_CAMPAIGNS_SERVICE_ID = "DOWELL10042"


############################################
# DOWELL SAMANTHA CAMPAIGNS SUBSERVICE IDs #
############################################

DOWELL_SAMANTHA_CAMPAIGNS_MAIL_SUBSERVICE_ID = "DOWELL100421"

DOWELL_SAMANTHA_CAMPAIGNS_SMS_SUBSERVICE_ID = "DOWELL100422"

DOWELL_SAMANTHA_CAMPAIGNS_SEARCH_IN_LIVING_LABS_SUBSERVICE_ID = "DOWELL100425"

DOWELL_SAMANTHA_CAMPAIGNS_EMAIL_VALIDATOR_SUBSERVICE_ID = "DOWELL100426"

DOWELL_WEBSITE_CRAWLER_SUBSERVICE_ID = "DOWELL100427"


#######################
# OBJECT API SETTINGS #
#######################

DEFAULT_OBJECT_DATABASE_CLASS = "api.database.SamanthaCampaignsDB"
